name: cric_11_admin
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/images/flags/1.png
  - assets/images/flags/2.png
  - assets/images/flags/3.png
  - assets/images/flags/4.png
  - assets/images/flags/5.png
  - assets/images/flags/6.png
  - assets/images/flags/7.png
  - assets/images/flags/8.png
  - assets/images/flags/9.png
  - assets/images/flags/10.png
  - assets/images/flags/11.png
  - assets/images/flags/12.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
