// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-fdWGT7kIn1tkXotU2_u-DKxeB4ulAyY',
    appId: '1:563930452959:web:ee446e4196f18836192a6a',
    messagingSenderId: '563930452959',
    projectId: 'cric11admin',
    authDomain: 'cric11admin.firebaseapp.com',
    storageBucket: 'cric11admin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcNL_pQ8DGsJ0K3w5iFNfpfUiKML1pwbg',
    appId: '1:563930452959:android:e72abd55ecf017ce192a6a',
    messagingSenderId: '563930452959',
    projectId: 'cric11admin',
    storageBucket: 'cric11admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDud1-ShiHyrz4svqhefe72u14BPlEuVqw',
    appId: '1:563930452959:ios:1946ccde11b9571e192a6a',
    messagingSenderId: '563930452959',
    projectId: 'cric11admin',
    storageBucket: 'cric11admin.appspot.com',
    iosBundleId: 'com.seesea.cric11Admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDud1-ShiHyrz4svqhefe72u14BPlEuVqw',
    appId: '1:563930452959:ios:6b0290babde731da192a6a',
    messagingSenderId: '563930452959',
    projectId: 'cric11admin',
    storageBucket: 'cric11admin.appspot.com',
    iosBundleId: 'com.seesea.cric11Admin.RunnerTests',
  );
}
